# Generated by Django 3.2.22 on 2023-10-22 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='game',
            options={'ordering': ['-year']},
        ),
        migrations.RemoveField(
            model_name='game',
            name='rating',
        ),
    ]
