# Generated by Django 3.2.22 on 2023-10-24 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0003_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='username',
        ),
    ]
