# Generated by Django 3.2.22 on 2023-10-28 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0006_auto_20231028_0007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='title',
            field=models.CharField(blank=True, max_length=80, unique=True),
        ),
    ]
